name: geo-cem
channels:
  - conda-forge
dependencies: # Installing with conda takes many minutes. Use: mamba env create -f environment.yml
  - pymt_cem # not needed with pymt=1.3.1 ; that version includes models by default
    # Needs to be a fresh install. Installing more modules for additional model components after the initial install errors with "Invalid spec, no package name found: <NULL>".
  # Comments below match versions in pymt_cem environment on explore.openearthscape.org jupyterlab
  - pymt #=1.3.1
  #- gimli.units=0.3.0
  #- model_metadata=0.7.0
  - geopandas
  - ipykernel # To use this environment in jupyter, run: python -m ipykernel install --user --name geo-cem --display-name geo-cem
  - nbformat # maybe nbconvert or jupyter?